### ISSUE TITLE
Url open plugin

### ISSUE THREAD

**Issue by dustdfg** [taconi/plugin-channel#22]
https://github.com/pjg11/micro-urlopen

**Comment by taconi** [comment]
The plugin does not yet have the repo.json file, you would need it to be able to add it to this list.
The [documentation](https://github.com/zyedidia/micro/blob/75b9a6cefed4fc325888ad93e356ec4f2ea1341d/runtime/help/plugins.md#plugin-manager) talks about this in more detail.

**Comment by taconi** [comment]
As soon as pr [#3](https://github.com/pjg11/micro-urlopen/pull/3) is accepted I will add this plugin

**Comment by taconi** [comment]
plugin added, thanks for the issue ❤️
